name: Other

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

jobs:
  mix_test:
    name: Scheduled job
    runs-on: ubuntu-latest
    steps:
      - run: echo 42
      - run: fail_miserably
